name: Deploy Blazor WASM to Ubuntu Server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependências
        run: dotnet restore

      - name: Build projeto
        run: dotnet build --configuration Release

      - name: Publicar projeto
        run: |
          cd InventoryWeb
          dotnet publish -c Release -o ../publish

      - name: Limpar a pasta de deploy no servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/inventory-front/*
            
      - name: Copiar arquivos para o servidor via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./publish/wwwroot/*" 
          target: "/var/www/inventory-front/"

      - name: Mover conteúdo para o lugar certo (caso publish/wwwroot foi copiado)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo mv /var/www/inventory-front/publish/wwwroot/* /var/www/inventory-front/
            sudo rm -rf /var/www/inventory-front/publish

      - name: Rodar comandos remotos (opcional)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
